import Sidebar from "@/components/sidebar";
import { SidebarContextProvider } from "@/context/useSidebar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen flex`}>
        <SidebarContextProvider>
          <Sidebar />
          <div className="flex-grow p-4 transition-all duration-300">
            {children}
          </div>
        </SidebarContextProvider>
      </body>
    </html>
  );
}
